# Generated by Django 3.2.5 on 2021-10-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='status_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='blocked',
        ),
        migrations.AddField(
            model_name='friendship',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='updated date'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=' created date'),
        ),
        migrations.DeleteModel(
            name='Block',
        ),
    ]
