# Generated by Django 3.2.4 on 2021-10-05 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211005_1100'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friendship',
            name='friend to user constraint',
        ),
    ]
