# Generated by Django 3.2.5 on 2021-10-05 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_friendship_friend to user constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='sent', max_length=20, verbose_name='friendship request status')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='first created date')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='friendship',
            name='user to friend constraint',
        ),
        migrations.AlterField(
            model_name='friendship',
            name='status_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='status change date'),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.UniqueConstraint(fields=('user', 'friend'), name='unique constraint'),
        ),
        migrations.AddField(
            model_name='friendshiprequest',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_to_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendshiprequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_from_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='requests',
            field=models.ManyToManyField(related_name='_api_user_requests_+', through='api.FriendshipRequest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='friendshiprequest',
            constraint=models.UniqueConstraint(fields=('user', 'friend'), name='request unique constraint'),
        ),
    ]
