# Generated by Django 3.2.5 on 2021-10-05 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211005_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.AddField(
            model_name='user',
            name='blocked',
            field=models.ManyToManyField(related_name='_api_user_blocked_+', through='api.Block', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='friendships',
            field=models.ManyToManyField(related_name='_api_user_friendships_+', through='api.Friendship', to=settings.AUTH_USER_MODEL),
        ),
    ]
